services:
  app:
    build:
      context: .
    container_name: financial-dashboard-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: financial-dashboard-db
    environment:
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${SPRING_DATASOURCE_USERNAME}
      - MYSQL_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
