services:
  app:
    build:
      context: ..
    container_name: dev-financial-dashboard-app
    ports:
      - "8081:8080"
    depends_on:
      - db
    env_file:
      - ./app.dev.env
    environment:
      SPRING_PROFILES_ACTIVE: dev

  db:
    image: mysql:8
    container_name: dev-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
