spring.application.name=demo

# MySql Configuration
spring.datasource.url=jdbc:mysql://db:3306/${DB_NAME}

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
